name: Lint

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/*
      - name: Log files
        run: ls
